In [40]:
import pandas as pd

games = pd.read_csv("data/games.csv")
matches = pd.read_csv("data/matches.csv")
tournaments = pd.read_csv("data/tour_meta.csv")

In [34]:
games['date'] = pd.to_datetime(games.date.str.split('(').str[0].str.strip())
games = games[pd.notna(games['date'])]
len(games)

5662

In [35]:
games.sort_values('date', inplace=True)
games

,match_id,game_id,match_title,tournament,date,game_duration,patch,blue_team,blue_result,blue_kills,...,vision_team1_wards_destroyed,vision_team1_wards_placed,vision_team2_wards_destroyed,vision_team2_wards_placed,jungle_share_15min_blue,jungle_share_15min_red,jungle_share_end_blue,jungle_share_end_red,voidgrubs_blue,voidgrubs_red
413,44432,44434,FPX vs Team WE,LPL Spring 2023,2023-01-14,44:52,v13.1,Funplus Phoenix,LOSS,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,44432,44433,FPX vs Team WE,LPL Spring 2023,2023-01-14,29:39,v13.1,Team WE,LOSS,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,44432,44432,FPX vs Team WE,LPL Spring 2023,2023-01-14,30:36,v13.1,Funplus Phoenix,LOSS,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,44435,44436,AL vs IG,LPL Spring 2023,2023-01-14,25:29,v13.1,Anyone s Legend,LOSS,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,44435,44435,AL vs IG,LPL Spring 2023,2023-01-14,46:02,v13.1,Anyone s Legend,LOSS,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5613,72947,72947,Top Esports vs BLG,Worlds 2025 Main Event,2025-10-25,28:19,v15.20,Top Esports,LOSS,10,...,44.0,98.0,43.0,96.0,46.8,53.2,42.3,57.7,3.0,0.0
5612,72950,72951,T1 vs MKOI,Worlds 2025 Main Event,2025-10-25,41:19,v15.20,T1,WIN,19,...,71.0,146.0,76.0,163.0,54.4,45.6,54.4,45.6,0.0,3.0
5611,72950,72950,T1 vs MKOI,Worlds 2025 Main Event,2025-10-25,32:54,v15.20,Movistar KOI,LOSS,10,...,66.0,121.0,54.0,128.0,49.3,50.7,47.7,52.3,3.0,0.0
5617,72944,72945,CFO vs FlyQuest,Worlds 2025 Main Event,2025-10-25,27:11,v15.20,FlyQuest,LOSS,5,...,36.0,103.0,43.0,80.0,51.6,48.4,45.0,55.0,3.0,0.0
5616,72944,72944,CFO vs FlyQuest,Worlds 2025 Main Event,2025-10-25,45:08,v15.20,CTBC Flying Oyster,WIN,21,...,64.0,165.0,74.0,178.0,45.3,54.7,49.9,50.1,3.0,0.0

In [39]:
len(games.blue_team.unique())

81

In [43]:
matches.sample(5)

,tournament_name,match_id,match_name,team1,team1_score,team2,team2_score,total_games,week,patch,date,url
5037,LEC 2025 Spring Season,65223,Fnatic vs SK Gaming,SK Gaming,2.0,Fnatic,0.0,2,WEEK1,15.60,2025-03-31,https://gol.gg/game/stats/65223/page-summary/
1574,LPL Summer 2023,49519,Top Esports vs WBG,Top Esports,2.0,Weibo Gaming,1.0,3,WEEK2,13.10,2023-06-11,https://gol.gg/game/stats/49519/page-summary/
2682,LEC Winter 2023,44935,Fnatic vs XL,Excel Esports,0.0,Fnatic,1.0,1,WEEK2,13.10,2023-01-29,https://gol.gg/game/stats/44935/page-game/
373,LPL Spring 2023,44990,IG vs EDG,Invictus Gaming,2.0,Edward Gaming,0.0,2,WEEK3,13.10,2023-02-01,https://gol.gg/game/stats/44990/page-summary/
4288,LCK Summer 2024,61072,NS vs FearX,FearX,2.0,Nongshim RedForce,0.0,2,WEEK6,14.14,2024-07-24,https://gol.gg/game/stats/61072/page-summary/

In [44]:
for t in matches.tournament_name.unique(): 
    print(t)

LEC Winter 2023
LEC Winter Groups 2023
LEC Winter Playoffs 2023
LPL Spring 2023
LEC Spring Season 2023
LEC Spring Groups 2023
LEC Spring Playoffs 2023
LPL Spring Playoffs 2023
LCS Spring 2023
LCS Spring Playoffs 2023
LCK Spring 2023
LCK Spring Playoffs 2023
MSI 2023
LPL Summer 2023
LEC Summer 2023
LEC Summer Groups 2023
LEC Summer Playoffs 2023
LPL Summer Playoffs 2023
LCK Summer 2023
LCK Summer Playoffs 2023
LCS Summer 2023
LCS Championship 2023
LPL Regional Finals 2023
LCK Regional Finals 2023
LEC Season Finals 2023
Worlds Qualifying Series 2023
Worlds Play-In 2023
Worlds Main Event 2023
LEC Winter Season 2024
LEC Winter Playoffs 2024
LPL Spring 2024
LEC Spring Season 2024
LEC Spring Playoffs 2024
LPL Spring Playoffs 2024
LCS Spring 2024
LCS Spring Playoffs 2024
LCK Spring 2024
LCK Spring Playoffs 2024
MSI 2024
LPL Summer Placements 2024
LPL Summer Season 2024
LEC Summer Season 2024
LCK Summer 2024
LPL Summer Playoffs 2024
LEC Summer Playoffs 2024
LCS Summer 2024
LCS Championship 2024
LPL Regional Finals 2024
LCK Regional Finals 2024
LEC Season Finals 2024
Esports World Cup 2024
Worlds Play-In 2024
Worlds Main Event 2024
LEC Winter 2025
LTA 2025 Split 1 Playoffs
LTA North 2025 Split 1
LCP 2025 Season Kickoff
LCP 2025 Season Kickoff Qualifying Series
LPL 2025 Split 1
LPL 2025 Split 1 Playoffs
LCK Cup 2025
LCK 2025 Rounds 1-2
LPL 2025 Split 2 Placements
LPL 2025 Split 2
LCP 2025 Mid Season
LTA North 2025 Split 2
LTA North 2025 Split 2 Playoffs
LPL 2025 Split 2 Playoffs
LEC 2025 Spring Season
LEC 2025 Spring Playoffs
LCK 2025 Road to MSI
2025 Mid-Season Invitational
Esports World Cup 2025
LEC 2025 Summer Season
LEC 2025 Summer Playoffs
LPL 2025 Grand Finals
LPL 2025 Regional Finals
LCK 2025 Season Play-In
LCK 2025 Season Playoffs
LTA 2025 Championship
Worlds 2025 Play-In
Worlds 2025 Main Event