In [6]:
import nba_api_module as nbpim
import pandas as pd

pd.set_option('display.max_columns', None)

TEST_GAME_ID = '0022400724'

In [8]:
pbp_df = nbpim.get_game_snapshots(TEST_GAME_ID)
snapshots = nbpim.extract_snapshots(pbp_df)
snapshots[1]

1 3.0
2 6.0
2 0.0
3 9.0
3 6.0
3 3.0
3 0.0
4 9.0
4 7.5
4 6.0
4 4.5
4 3.0
4 1.5
4 0.0

{'period': 2,
 'time_remaining_period': 360,
 'home_score': 43,
 'away_score': 50,
 'score_diff': -7,
 'home_points_last_6min': 6,
 'away_points_last_6min': 17,
 'momentum_diff6': -11,
 'home_points_last_4min': 6,
 'away_points_last_4min': 17,
 'momentum_diff4': -11,
 'home_points_last_2min': 4,
 'away_points_last_2min': 7,
 'momentum_diff2': -3,
 'run': 0,
 'pace_live': 4.83,
 'home_top_player_points_live': 13,
 'away_top_player_points_live': 13,
 'home_foul_count': 4,
 'away_foul_count': 2,
 'home_foul_trouble_players': 0,
 'away_foul_trouble_players': 0}

In [56]:
# Inactive players

from nba_api.stats.endpoints import boxscoresummaryv2

bs_raw = boxscoresummaryv2.BoxScoreSummaryV2(game_id='0022400001')
bs = bs_raw.get_dict()

for x in bs['resultSets']:
    if x['name'] == 'InactivePlayers':
        print(x)

        headers = x['headers']
        rows = x['rowSet']
        
        # DataFrame készítése
        df = pd.DataFrame(rows, columns=headers)
        display(df)

{'name': 'InactivePlayers', 'headers': ['PLAYER_ID', 'FIRST_NAME', 'LAST_NAME', 'JERSEY_NUM', 'TEAM_ID', 'TEAM_CITY', 'TEAM_NAME', 'TEAM_ABBREVIATION'], 'rowSet': [[204001, 'Kristaps', 'Porzingis', '8   ', 1610612738, 'Boston', 'Celtics', 'BOS'], [1630531, 'Jaden', 'Springer', '44  ', 1610612738, 'Boston', 'Celtics', 'BOS'], [1631120, 'JD', 'Davison', '20  ', 1610612738, 'Boston', 'Celtics', 'BOS'], [1641817, 'Anton', 'Watson', '28  ', 1610612738, 'Boston', 'Celtics', 'BOS'], [1641723, 'Kobe', 'Bufkin', '4   ', 1610612737, 'Atlanta', 'Hawks', 'ATL'], [1641754, 'Seth', 'Lundy', '3   ', 1610612737, 'Atlanta', 'Hawks', 'ATL'], [1629027, 'Trae', 'Young', '11  ', 1610612737, 'Atlanta', 'Hawks', 'ATL'], [1629631, "De'Andre", 'Hunter', '12  ', 1610612737, 'Atlanta', 'Hawks', 'ATL'], [203469, 'Cody', 'Zeller', '41  ', 1610612737, 'Atlanta', 'Hawks', 'ATL'], [203992, 'Bogdan', 'Bogdanović', '13  ', 1610612737, 'Atlanta', 'Hawks', 'ATL']]}

C:\Users\Adam\AppData\Local\Temp\ipykernel_23856\2799628258.py:3: UserWarning: BoxScoreSummaryV2 has known data availability issues. Data may be missing for games on or after 4/10/2025. Users should moving to BoxScoreSummaryV3 or verify data completeness for their specific use cases and implement appropriate error handling.
  bs_raw = boxscoresummaryv2.BoxScoreSummaryV2(game_id='0022400001')

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION
0,204001,Kristaps,Porzingis,8,1610612738,Boston,Celtics,BOS
1,1630531,Jaden,Springer,44,1610612738,Boston,Celtics,BOS
2,1631120,JD,Davison,20,1610612738,Boston,Celtics,BOS
3,1641817,Anton,Watson,28,1610612738,Boston,Celtics,BOS
4,1641723,Kobe,Bufkin,4,1610612737,Atlanta,Hawks,ATL
5,1641754,Seth,Lundy,3,1610612737,Atlanta,Hawks,ATL
6,1629027,Trae,Young,11,1610612737,Atlanta,Hawks,ATL
7,1629631,De'Andre,Hunter,12,1610612737,Atlanta,Hawks,ATL
8,203469,Cody,Zeller,41,1610612737,Atlanta,Hawks,ATL
9,203992,Bogdan,Bogdanović,13,1610612737,Atlanta,Hawks,ATL

In [37]:
games = nbpim.get_season_game_log('2025-26')
games

Total games found: 382

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1610612745,HOU,Houston Rockets,0022500001,2025-10-21,HOU @ OKC,L,290,43,97,0.443,11,39,0.282,27,31,0.871,16,36,52,23,6,5,25,26,124,-1,1
1,22025,1610612744,GSW,Golden State Warriors,0022500002,2025-10-21,GSW @ LAL,W,240,38,78,0.487,17,40,0.425,26,29,0.897,9,31,40,29,10,4,19,27,119,10,1
2,22025,1610612747,LAL,Los Angeles Lakers,0022500002,2025-10-21,LAL vs. GSW,L,240,42,77,0.545,8,32,0.250,17,28,0.607,7,32,39,23,7,2,20,21,109,-10,1
3,22025,1610612760,OKC,Oklahoma City Thunder,0022500001,2025-10-21,OKC vs. HOU,W,290,46,104,0.442,13,52,0.250,20,25,0.800,11,27,38,29,12,4,12,27,125,1,1
4,22025,1610612737,ATL,Atlanta Hawks,0022500082,2025-10-22,ATL vs. TOR,L,240,38,90,0.422,10,35,0.286,32,37,0.865,8,26,34,25,7,6,16,24,118,-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,22025,1610612761,TOR,Toronto Raptors,0022500230,2025-11-15,TOR @ IND,W,240,48,87,0.552,7,30,0.233,26,42,0.619,8,38,46,29,13,3,14,20,129,18,1
378,22025,1610612749,MIL,Milwaukee Bucks,0022500231,2025-11-15,MIL vs. LAL,L,240,32,80,0.400,15,39,0.385,16,24,0.667,12,27,39,20,6,4,17,23,95,-24,1
379,22025,1610612750,MIN,Minnesota Timberwolves,0022500232,2025-11-15,MIN vs. DEN,L,240,41,88,0.466,10,34,0.294,20,23,0.870,8,32,40,23,9,7,13,27,112,-11,2
380,22025,1610612743,DEN,Denver Nuggets,0022500232,2025-11-15,DEN @ MIN,W,240,39,83,0.470,14,29,0.483,31,38,0.816,10,37,47,29,9,6,13,19,123,11,2
381,22025,1610612763,MEM,Memphis Grizzlies,0022500228,2025-11-15,MEM @ CLE,L,240,31,86,0.360,9,32,0.281,29,40,0.725,11,35,46,21,9,5,15,25,100,-8,1

In [ ]:
# GameID metadata

from nba_api.stats.endpoints import boxscoretraditionalv3

game_id = TEST_GAME_ID

bs = boxscoretraditionalv3.BoxScoreTraditionalV3(game_id=game_id)
d = bs.get_dict()

time = d['meta']['time']
print(time)

bst = d['boxScoreTraditional']

print(bst['homeTeam']['teamName'])
print(bst['awayTeam']['teamName'])

In [ ]:
from nba_api.stats.endpoints import teamdashboardbygeneralsplits
import pandas as pd

team_id = 1610612747   # pl. Los Angeles Lakers
season = "2023-24"

# lekérés
dashboard = teamdashboardbygeneralsplits.TeamDashboardByGeneralSplits(
    team_id=team_id,
    season=season,
    season_type_all_star="Regular Season"
)

# a válasz struktúrája
data = dashboard.get_dict()

# Az NBA API több táblát ad vissza — a "OverallTeamDashboard" lesz a fő
overall = data["resultSets"][0]

headers = overall["headers"]
rows = overall["rowSet"]

df = pd.DataFrame(rows, columns=headers)

display(df.head())

In [ ]:
from nba_api.stats.endpoints import leaguegamelog
import pandas as pd

def get_games(season="2023-24"):
    log = leaguegamelog.LeagueGameLog(
        season=season,
        season_type_all_star="Regular Season"
    )
    data = log.get_dict()
    
    df = pd.DataFrame(
        data['resultSets'][0]['rowSet'],
        columns=data['resultSets'][0]['headers']
    )
    
    # dátum konvertálása
    df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"])
    return df

df = get_games("2023-24")

start = pd.to_datetime("2024-01-01")
end   = pd.to_datetime("2024-02-01")

filtered = df[
    (df["TEAM_ID"] == 1610612747) &
    (df["GAME_DATE"] >= start) &
    (df["GAME_DATE"] <= end)
]

display(filtered.columns)

team_stats = filtered.groupby("TEAM_ID").agg({
    "PTS": "mean",
    "FGM": "mean",
    "FGA": "mean",
    "REB": "mean",
    "AST": "mean",
    "PLUS_MINUS": "mean"
}).reset_index()

print(team_stats)

In [ ]:
from nba_api.stats.endpoints import leaguedashteamstats

lds_log = leaguedashteamstats.LeagueDashTeamStats(
    season='2024-25',
    date_from_nullable='2024-10-01',
    date_to_nullable='2024-11-01',
    measure_type_detailed_defense='Advanced',
    season_type_all_star='Regular Season'
)

lds = lds_log.get_dict()
lds

headers = lds['resultSets'][0]['headers']
rows = lds['resultSets'][0]['rowSet']

for i in range(len(rows)):
    if rows[i][1] != "Houston Rockets":
        continue
    for j in range(len(headers)):
        print(f"{headers[j]}: {rows[i][j]}")

In [ ]:
from nba_api.stats.endpoints import leaguedashplayerstats 

ldp_log = leaguedashplayerstats.LeagueDashPlayerStats(
    season='2024-25',
    date_from_nullable='2024-10-25',
    date_to_nullable='2024-11-01',
    measure_type_detailed_defense='Advanced',
    season_type_all_star='Regular Season'
)

ldp = ldp_log.get_dict()
len(ldp['resultSets'][0]['rowSet']) # 416, all players

headers = ldp['resultSets'][0]['headers']
values = ldp['resultSets'][0]['rowSet'][120]

for i in range(len(headers)):
    print(f"{headers[i]}: {values[i]}")